#spring.datasource.url=jdbc:mysql://localhost:3306/UFVBay
#spring.datasource.username=root
#spring.datasource.password=testPassword
#
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=update




spring.datasource.url=jdbc:postgresql://app-732b29e9-4f86-43fb-be78-753a4f5fa16e-do-user-26823518-0.e.db.ondigitalocean.com:25060/dbufvbay?sslmode=require
spring.datasource.username=dbufvbay
spring.datasource.password=AVNS_IU4lg_JazlDiOeKFRCj

# Hibernate dialect for Postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update



#secret key
app.jwt-secret=36f0f4b6056ac4d0a4b7dbb7c94597c1d44c9d6c84dc370121deedbde5049560
app.jwt-expiration-milliseconds=6048000000


#Cloudinary
cloudinary.cloud-name=dc1hhugjd
cloudinary.api-key=128879859199394
cloudinary.api-secret=wRkD_WCK1GxoRKURygS2XN6Ou6w


